discord:
  token: "IDE_IRD_A_DISCORD_BOT_TOKENED"
  mainChannelId: "DISCORD_CSATORNA_ID_A_CHAT_BRIDGEHEZ"
  logChannelId: "LOG_CSATORNA_ID"
  guild-id: "DISCORD_SZERVER_ID"
  ticket:
    category-id: "KATEGÃ“RIA_ID"
    log-channel-id: "TICKET_LOG_CSATORNA_ID"
    panel-channel-id: "PANEL_CSATORNA_ID"
  chat:
    channel-id: "CHAT_BRIDGE_CSATORNA_ID"
  link:
      log-channel-id: "LOG_CSATORNA_ID"